### PR TITLE
Add npm tag logic in deploy script

### PR DESCRIPTION
**Pull request by nmarley**

### CODE REVIEW

**Comment by shumkov** [comment]
I think we don't need it. That's enough https://github.com/dashevo/js-dpp/blob/v0.8/package.json#L21

**Comment by nmarley** [comment]
@shumkov When you want to release v0.8.1 stable, you will want a `latest` tag, right? How do you propose to do that?

We want to keep it automated via tags, not manually pushed. Right?

**Comment by shumkov** [comment]
@nmarley I thought when we release `v0.8.0` as stable before we merge `v0.8` branch into `master` we remove `dev` postfix from `version` and `tag` option from `publishConfig`.

**Comment by nmarley** [comment]
> I thought when we release v0.8.0 as stable before we merge v0.8 branch into master

What about v0.8.1? Or any other v0.8.x version? If you only plan to release v0.8.0 with this then why are we calling the branch called v0.8? Lets just call it v0.8.0 then. Otherwise it doesn't make sense.

**Comment by shumkov** [comment]
I think we will release v0.8.1 only when it becomes stable. Before it will be only v0.8.0-dev.N

**Comment by shumkov** [comment]
I don’t mind to rename it to `v0.8.0` or `v0.8.0-dev` or `v0.8-dev`. Actually, with dev postfix will be much clear.

**Comment by nmarley** [comment]
Going to close this per discussion, but I think this will crop up again if we need to release multiple stable versions. If we rename the branch we will need to update Travis also.

**Pull request closed without merging**
