### PR TITLE
fix!: subdomain rules were checked against subdomain instead of parent domain

### PR DESCRIPTION
**Pull request by jawid-h**
## Issue being fixed or feature implemented

Subdomain registration rules were checked against currently created domain instead of it's parent domain

## Breaking Changes

Only second-level domain owner is allowed to create its subdomains

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

### CODE REVIEW

**Review by shumkov — APPROVED** [review]
Good catch! 👍

**Review by shumkov — CHANGES_REQUESTED** [review]
Don’t we need to update unit tests?

**Review by shuplenkov — APPROVED** [review]

**Comment by shuplenkov** [comment]
> Don’t we need to update unit tests?

I don't think it's possible, because we always use allowSubdomains = false condition. If we try to do so, we'll have another trigger error. The thing is that we tried to compare it from childDocumentTransition instead of the parent.

**Comment by shumkov** [comment]
We use `true` for TLD, so we can test both cases TLD and subdomain.

**Review by shumkov — APPROVED** [review]
Great, thank you!

**Pull request merged**
